apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: maven-app
  name: maven-app
spec:
  replicas: {{.values.replicaCount}}
  selector:
    matchLabels:
      app: maven-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maven-app
    spec:
      containers:
      - image: {{.values.repository.image}}
        name: java-web-app
        ports:
        - containerPort: 8080
        resources: {}
status: {}
